In [1]:
# Dependencies
import numpy as np
import pandas as pd
import requests

In [2]:
# Read the data
cont_data_df = pd.read_csv("./Resources/Clean_Committee_2017.csv", low_memory=False)
cont_data_df.head()

,Unnamed: 0,Election,CandidateID,CandidateName,Date,Name,ContributerType,BoroughName,City,State,ZipCode,ContributionState,Amount,MatchAmt,PrevAmt,PayMethod,TotalAmount
0,0,2017,326.0,"de Blasio, Bill",NaN,1199/SEIU NYS Pol. Action Fund,Political Action Committee,Manhattan,New York,NY,10108,NaN,4950.0,0,0,Check,4950.0
1,1,2017,326.0,"de Blasio, Bill",NaN,32BJ United ADF,Political Action Committee,Manhattan,New York,NY,10011,NaN,2500.0,0,0,Check,2500.0
2,2,2017,326.0,"de Blasio, Bill",NaN,32BJ United ADF,Political Action Committee,Manhattan,New York,NY,10011,NaN,2450.0,0,2500,Check,4950.0
3,3,2017,326.0,"de Blasio, Bill",NaN,ACEC New York City PAC,Political Action Committee,Manhattan,New York,NY,10018,NaN,4950.0,0,0,Check,4950.0
4,4,2017,326.0,"de Blasio, Bill",NaN,AFSCME DC 1707 PAC,Political Action Committee,Manhattan,New York,NY,10013,NaN,500.0,0,0,Check,500.0

In [3]:
# Drop unnecessary columns
cont_data_df = cont_data_df.drop(['CandidateID', 'Date', 'ContributionState', 'ContributerType', 'MatchAmt', 'PayMethod'], axis=1)
cont_data_df

,Unnamed: 0,Election,CandidateName,Name,BoroughName,City,State,ZipCode,Amount,PrevAmt,TotalAmount
0,0,2017,"de Blasio, Bill",1199/SEIU NYS Pol. Action Fund,Manhattan,New York,NY,10108,4950.0,0,4950.0
1,1,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2500.0,0,2500.0
2,2,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2450.0,2500,4950.0
3,3,2017,"de Blasio, Bill",ACEC New York City PAC,Manhattan,New York,NY,10018,4950.0,0,4950.0
4,4,2017,"de Blasio, Bill",AFSCME DC 1707 PAC,Manhattan,New York,NY,10013,500.0,0,500.0
...,...,...,...,...,...,...,...,...,...,...,...
232,232,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,4950.0,4950,9900.0
233,233,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,-4950.0,0,-4950.0
234,234,2017,"de Blasio, Bill","USW D-4 NY, NJ, DE, ME",Other,Cheektowaga,NY,14225,2500.0,0,2500.0
235,235,2017,"de Blasio, Bill",Van Bramer 2017,Manhattan,New York,NY,10016,4950.0,0,4950.0
236,236,2017,"de Blasio, Bill",Voice of Teachers for Educatio,Other,Latham,NY,12110,4950.0,0,4950.0

In [4]:
# Drop all blank columns
cont_data_df = cont_data_df.dropna()
cont_data_df

,Unnamed: 0,Election,CandidateName,Name,BoroughName,City,State,ZipCode,Amount,PrevAmt,TotalAmount
0,0,2017,"de Blasio, Bill",1199/SEIU NYS Pol. Action Fund,Manhattan,New York,NY,10108,4950.0,0,4950.0
1,1,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2500.0,0,2500.0
2,2,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2450.0,2500,4950.0
3,3,2017,"de Blasio, Bill",ACEC New York City PAC,Manhattan,New York,NY,10018,4950.0,0,4950.0
4,4,2017,"de Blasio, Bill",AFSCME DC 1707 PAC,Manhattan,New York,NY,10013,500.0,0,500.0
...,...,...,...,...,...,...,...,...,...,...,...
232,232,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,4950.0,4950,9900.0
233,233,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,-4950.0,0,-4950.0
234,234,2017,"de Blasio, Bill","USW D-4 NY, NJ, DE, ME",Other,Cheektowaga,NY,14225,2500.0,0,2500.0
235,235,2017,"de Blasio, Bill",Van Bramer 2017,Manhattan,New York,NY,10016,4950.0,0,4950.0
236,236,2017,"de Blasio, Bill",Voice of Teachers for Educatio,Other,Latham,NY,12110,4950.0,0,4950.0

In [5]:
# Regularize numerical columns
cont_data_df['ZipCode'] = cont_data_df['ZipCode'].astype(int)
cont_data_df['Amount'] = cont_data_df['Amount'].astype(int)
cont_data_df['PrevAmt'] = cont_data_df['PrevAmt'].astype(int)
cont_data_df['TotalAmount'] = cont_data_df['TotalAmount'].astype(int)
cont_data_df

C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,Unnamed: 0,Election,CandidateName,Name,BoroughName,City,State,ZipCode,Amount,PrevAmt,TotalAmount
0,0,2017,"de Blasio, Bill",1199/SEIU NYS Pol. Action Fund,Manhattan,New York,NY,10108,4950,0,4950
1,1,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2500,0,2500
2,2,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2450,2500,4950
3,3,2017,"de Blasio, Bill",ACEC New York City PAC,Manhattan,New York,NY,10018,4950,0,4950
4,4,2017,"de Blasio, Bill",AFSCME DC 1707 PAC,Manhattan,New York,NY,10013,500,0,500
...,...,...,...,...,...,...,...,...,...,...,...
232,232,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,4950,4950,9900
233,233,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,-4950,0,-4950
234,234,2017,"de Blasio, Bill","USW D-4 NY, NJ, DE, ME",Other,Cheektowaga,NY,14225,2500,0,2500
235,235,2017,"de Blasio, Bill",Van Bramer 2017,Manhattan,New York,NY,10016,4950,0,4950
236,236,2017,"de Blasio, Bill",Voice of Teachers for Educatio,Other,Latham,NY,12110,4950,0,4950

In [6]:
# Converting dollar amounts according to inflation (figures derived from https://www.usinflationcalculator.com/)
cont_data_df['ElectionTemp'] = cont_data_df['Election']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2001, 'AdjustedAmount'] = cont_data_df['Amount']*1.55
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2005, 'AdjustedAmount'] = cont_data_df['Amount']*1.40
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2009, 'AdjustedAmount'] = cont_data_df['Amount']*1.28
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2013, 'AdjustedAmount'] = cont_data_df['Amount']*1.17
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2017, 'AdjustedAmount'] = cont_data_df['Amount']*1.11
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2021, 'AdjustedAmount'] = cont_data_df['Amount']*1.00

cont_data_df['ElectionTemp'] = cont_data_df['Election']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2001, 'AdjustedPrevAmt'] = cont_data_df['PrevAmt']*1.55
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2005, 'AdjustedPrevAmt'] = cont_data_df['PrevAmt']*1.40
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2009, 'AdjustedPrevAmt'] = cont_data_df['PrevAmt']*1.28
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2013, 'AdjustedPrevAmt'] = cont_data_df['PrevAmt']*1.17
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2017, 'AdjustedPrevAmt'] = cont_data_df['PrevAmt']*1.11
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2021, 'AdjustedPrevAmt'] = cont_data_df['PrevAmt']*1.00

cont_data_df['ElectionTemp'] = cont_data_df['Election']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2001, 'AdjustedTotalAmount'] = cont_data_df['TotalAmount']*1.55
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2005, 'AdjustedTotalAmount'] = cont_data_df['TotalAmount']*1.40
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2009, 'AdjustedTotalAmount'] = cont_data_df['TotalAmount']*1.28
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2013, 'AdjustedTotalAmount'] = cont_data_df['TotalAmount']*1.17
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2017, 'AdjustedTotalAmount'] = cont_data_df['TotalAmount']*1.11
cont_data_df['Election'] = cont_data_df['ElectionTemp']
cont_data_df.loc[cont_data_df['ElectionTemp'] == 2021, 'AdjustedTotalAmount'] = cont_data_df['TotalAmount']*1.00
cont_data_df

C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0,Election,CandidateName,Name,BoroughName,City,State,ZipCode,Amount,PrevAmt,TotalAmount,ElectionTemp,AdjustedAmount,AdjustedPrevAmt,AdjustedTotalAmount
0,0,2017,"de Blasio, Bill",1199/SEIU NYS Pol. Action Fund,Manhattan,New York,NY,10108,4950,0,4950,2017,5494.5,0.0,5494.5
1,1,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2500,0,2500,2017,2775.0,0.0,2775.0
2,2,2017,"de Blasio, Bill",32BJ United ADF,Manhattan,New York,NY,10011,2450,2500,4950,2017,2719.5,2775.0,5494.5
3,3,2017,"de Blasio, Bill",ACEC New York City PAC,Manhattan,New York,NY,10018,4950,0,4950,2017,5494.5,0.0,5494.5
4,4,2017,"de Blasio, Bill",AFSCME DC 1707 PAC,Manhattan,New York,NY,10013,500,0,500,2017,555.0,0.0,555.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,232,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,4950,4950,9900,2017,5494.5,5494.5,10989.0
233,233,2017,"de Blasio, Bill",United Food and Commercial Wor,Other,Washington,DC,20006,-4950,0,-4950,2017,-5494.5,0.0,-5494.5
234,234,2017,"de Blasio, Bill","USW D-4 NY, NJ, DE, ME",Other,Cheektowaga,NY,14225,2500,0,2500,2017,2775.0,0.0,2775.0
235,235,2017,"de Blasio, Bill",Van Bramer 2017,Manhattan,New York,NY,10016,4950,0,4950,2017,5494.5,0.0,5494.5
236,236,2017,"de Blasio, Bill",Voice of Teachers for Educatio,Other,Latham,NY,12110,4950,0,4950,2017,5494.5,0.0,5494.5

In [7]:
# Export cleaned data
cont_data_df.to_csv("./Resources/Clean_Committee_2017.csv", encoding='utf-8', index=False)

In [ ]:
# Read the data for the next file
cont_data2_df = pd.read_csv("./Resources/Clean_Individual_2017.csv", low_memory=False)
cont_data2_df.head()

In [ ]:
# Drop unnecessary columns
cont_data2_df = cont_data2_df.drop(['CandidateID', 'Date', 'ContributionState', 'ContributerType', 'MatchAmt', 'PayMethod'], axis=1)
cont_data2_df

In [ ]:
# Regularize numerical columns
cont_data2_df['ZipCode'] = cont_data2_df['ZipCode'].dropna()
cont_data2_df['ZipCode'] = cont_data2_df['ZipCode'].round(2)
cont_data2_df['Amount'] = cont_data2_df['Amount'].round(2)
cont_data2_df['PrevAmt'] = cont_data2_df['PrevAmt'].round(2)
cont_data2_df['TotalAmount'] = cont_data2_df['TotalAmount'].round(2)
cont_data2_df

In [ ]:
# Converting dollar amounts according to inflation (figures derived from https://www.usinflationcalculator.com/)
cont_data2_df['ElectionTemp'] = cont_data2_df['Election']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2001, 'AdjustedAmount'] = cont_data2_df['Amount']*1.55
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2005, 'AdjustedAmount'] = cont_data2_df['Amount']*1.40
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2009, 'AdjustedAmount'] = cont_data2_df['Amount']*1.28
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2013, 'AdjustedAmount'] = cont_data2_df['Amount']*1.17
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2017, 'AdjustedAmount'] = cont_data2_df['Amount']*1.11
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2021, 'AdjustedAmount'] = cont_data2_df['Amount']*1.00

cont_data2_df['ElectionTemp'] = cont_data2_df['Election']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2001, 'AdjustedPrevAmt'] = cont_data2_df['PrevAmt']*1.55
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2005, 'AdjustedPrevAmt'] = cont_data2_df['PrevAmt']*1.40
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2009, 'AdjustedPrevAmt'] = cont_data2_df['PrevAmt']*1.28
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2013, 'AdjustedPrevAmt'] = cont_data2_df['PrevAmt']*1.17
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2017, 'AdjustedPrevAmt'] = cont_data2_df['PrevAmt']*1.11
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2021, 'AdjustedPrevAmt'] = cont_data2_df['PrevAmt']*1.00

cont_data2_df['ElectionTemp'] = cont_data2_df['Election']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2001, 'AdjustedTotalAmount'] = cont_data2_df['TotalAmount']*1.55
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2005, 'AdjustedTotalAmount'] = cont_data2_df['TotalAmount']*1.40
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2009, 'AdjustedTotalAmount'] = cont_data2_df['TotalAmount']*1.28
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2013, 'AdjustedTotalAmount'] = cont_data2_df['TotalAmount']*1.17
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2017, 'AdjustedTotalAmount'] = cont_data2_df['TotalAmount']*1.11
cont_data2_df['Election'] = cont_data2_df['ElectionTemp']
cont_data2_df.loc[cont_data2_df['ElectionTemp'] == 2021, 'AdjustedTotalAmount'] = cont_data2_df['TotalAmount']*1.00
cont_data2_df

In [ ]:
# Export cleaned data
cont_data_df.to_csv("./Resources/Clean_Individual_2017_Revised.csv", encoding='utf-8', index=False)